"""Proves the AU AI Act was parsed propely, and fails loudly is it is not"""

import json
from collections import Counter
from pathlib import Path

EXPECTED_ARTICLE_COUNT = 113

def load(path: str) -> list[dict]:
    """Loads the EU AI Articles and returns the structured records"""
    with open(path, encoding="utf-8") as f:
        return [json.loads(line) for line in f]

def validate(records: list[dict]) -> None:
    """Does a few checks on the records of the EU AI Act data"""
    failures = []

    #check whether all 113 articles have been parsed
    articles_seen = set()
    for r in records:
        articles_seen.add(r["article_num"])
    if len(articles_seen) != EXPECTED_ARTICLE_COUNT:
        missing = set(range(1, EXPECTED_ARTICLE_COUNT + 1)) - articles_seen
        failures.append(f"Expected clauses from all {EXPECTED_ARTICLE_COUNT} articles, missing entirely: {sorted(missing)}")

    for r in records:
        ids = [r["chunk_id"]]
    duplicates = [] #checks for duplicates
    for i, n in Counter(ids).items():
        if n > 1:
            duplicates.append(i)
    if duplicates:
        failures.append(f"Duplicate chunk_ids: {duplicates}")

    for r in records:
        rid = r["display_id"]

        for field in ("text", "article_title", "display_id"):
            if not r[field] or not r[field].strip():
                failures.append(f"{rid}: empty {field}") #checks that all important fields are not empty

        if "<" in r["text"] or ">" in r["text"]:
            failures.append(f"{rid}: HTML leaked into text") #checks for HTML leakage

        if "  " in r["text"]:
            failures.append(f"{rid}: double space, normalisation failed") #checks for normalisation failure

        if r["text"].startswith("Related:"):
            failures.append(f"{rid}: Related-recital line leaked into text") #specific to EU AI Act, means teh filtrering done by the parser of the related recitals lines did not work

        if "Generated by CLaiRK" in r["text"] or "machine-generated translation" in r["text"]:
            failures.append(f"{rid}: Summary block leaked into text") # also another check specific to EU AI Act, means filtering of AI-generated summary did not work

    if failures:
        print(f"FAILED with {len(failures)} problems:\n")
        for f in failures[:30]:
            print(f" {f}")
        if len(failures) > 30:
            print(f" ... and {len(failures) - 30} more")
        raise SystemExit(1)

    print(f"PASSED: {len(records)} clauses across {len(articles_seen)} articles")

if __name__ == "__main__":
    validate(load("corpus/parsed/eu_ai_act.jsonl"))

    
    