"""Continuation of the inspection of the EU AI html. Refer to scripts/inspect_eu_macro.py for context"""

from lxml import html

doc = html.parse("corpus/raw/eu_articles/article_14.html").getroot()

body = doc.xpath("//body")[0]
all_elements = body.xpath(".//*") #any element, of any kind, at any depth, below body. result is a flat list of every single tag in the whole visible page in order

#find the index positions of our two indicator headings, as we know that the content lies between these headings
summary_idx = None
recitals_idx = None 
for i, element in enumerate(all_elements):
    text = " ".join(element.text_content().split())
    if element.tag == "h4" and text == "Summary":
        summary_idx = i
    if element.tag == "h4" and text == "Suitable Recitals":
        recitals_idx = i

print(f"Summary heading at position {summary_idx}")
print(f"Suitable Recitals heading at position {recitals_idx}")

#Look at what is in between the headers, tag names and short previes
between = all_elements[summary_idx:recitals_idx + 1]
for element in between:
    text = " ".join(element.text_content().split()) #normalises
    print(f"{element.tag:10} class={element.get('class')!r:30} :: {text[:60]}")

""" Findings: 
    1. Summary block (generated by the AI) has a distinct class that we can key off directly - 'aia-clairk-summary-content section'
    2. legal text also has its own distinct class, and the numbered paaragraphs each have its own clan <p> tag with no class
    3. After checking Article 2, it has been confirmed that the class name patter, et_pd_post_content_0_tb_body hols no matter which article. the 0 does not change
    4. We also realised afte checking article 2 that there are some 'Related aticles: ...' paragraphs wrapped in <p> tags in the content. Will have to filter these out in the parser.
    """